### ISSUE TITLE
SKR_3

### ISSUE THREAD

**Issue by atong9033** [TeamGloomy/Configurator#2]
Hi, when will you add the SKR_3 board to the configurator ? now which board should I choose to create the configuration?

**Comment by jaysuk** [comment]
I'll look at getting it added in the next day or so.

Thanks,

Jay

**Comment by jaysuk** [comment]
in the meantime use the SKR2 and change the board.txt name to biquskr_3
Thanks,

Jay

**Comment by atong9033** [comment]
Thanks)
