### ISSUE TITLE
SKR__3

### ISSUE THREAD

**Issue by atong9033** [TeamGloomy/Configurator#3]
I'm sorry for distracting.....but... In the configurator, you need to add a selection of the TMC2209_EZ driver with an adapter. Sensorless does not work. The axis moves 5 mm in the opposite direction from the end cap and nothing else happens, and the board believes that the axis is at home. I think this is due to the lack of two diagnostic pins on the EZ driver. Most likely they are redefined to other pins. I installed a regular 2209 and the axle started parking.

**Comment by jaysuk** [comment]
any chance you could jump on our discord and discuss this further? https://discord.gg/uS97Qs7
i've not tested sensorless homing on the SKR3EZ

**Comment by atong9033** [comment]
ok) thanks)
